### ISSUE TITLE
“https://bitbucket.org/stoneleaf/enum34” is invalid.

### ISSUE THREAD

**Issue by LXQQQ** [ethanfurman/enum34#1]
Hello, Ethan Furman.
When I go to “https://pypi.org/project/enum34/”, it says "Repository and Issue Tracker at https://bitbucket.org/stoneleaf/enum34".
But “https://bitbucket.org/stoneleaf/enum34” is invalid.
I wonder where is the community source code repository of enum34 now.
And where is the vulnerability disclosure address of enum34 now?

**Comment by ethanfurman** [comment]
enum34 is no longer maintained, use aenum as a replacement.

I have uploaded the code here for posterity.

If there is a security vulnerability you can email me privately.

**Comment by LXQQQ** [comment]
OK, I know. Thank you very much.
